ALTER TABLE payments ADD COLUMN IF NOT EXISTS cashfree_order_id TEXT UNIQUE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS course_slug TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS skill_name TEXT;
